.TH pin-hwmon 1 "v1.1.0" "pin-hwmon" "User Commands"
.SH NAME
pin-hwmon \- pin stable /etc/hwmon symlinks
.SH SYNOPSIS
.B pin-hwmon
.RI [ --quiet ]
.RI [ --no-egg ]
.RI [ --dry-run ]
.RI [ --relink ]
.RI [ --print ]
.SH DESCRIPTION
Pins stable symlinks for CPU/GPU sensors. Honors HWMON_ROOT for testing and /etc/pin-hwmon.conf.